{
 "title": "LinkRouter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h,2h,4h,8h" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(linkrouter_requests[$interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Requests by Route (Last $interval)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(linkrouter_requests[$interval])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests (Last $interval)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(linkrouter_404_requests[$interval])) + sum(increase(linkrouter_requests[$interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "404 Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(linkrouter_404_requests[$interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Number of total successful Requests (Last $interval)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(linkrouter_requests[$interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of 404 Requests (Last $interval)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(linkrouter_404_requests[$interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}